apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: wireguard-and-home-ip-whitelist
  namespace: {{ .Values.namespace }}
spec:
  ipWhiteList:
    sourceRange:
      - 10.42.0.0/16
      - 192.168.0.0/24
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: {{ .Values.namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
